//### AUTOMATICALLY GENERATED BY src/covarianceMatrixStudy.cpp ###//
//### DATASET: TT_FCNC-TtoHJ_aThadronic_HToaa_eta_hct-MadGraph5-pythia8
#include <TMatrixD.h>
#include <TVectorD.h>

double w_boson_mass = 80.379;//GeV
double top_quark_mass = 172.5;//GeV

double Chi2_calculator_simple(double w_mass, double t_mass){
    TVectorD vec_mass(2);
    vec_mass(0) = w_mass - w_boson_mass;
    vec_mass(1) = t_mass - top_quark_mass;
    TMatrixD matrix(2,2);
    matrix(0,0) = 341.00; matrix(0,1) =   0.00;
    matrix(1,0) =   0.00; matrix(1,1) = 821.02;
    return matrix.Invert()*vec_mass*vec_mass;
}

double Chi2_calculator_modified(double w_mass, double t_mass){
    TVectorD vec_mass(2);
    vec_mass(0) = w_mass - w_boson_mass;
    vec_mass(1) = t_mass - top_quark_mass;
    TMatrixD matrix(2,2);
    matrix(0,0) = 341.00; matrix(0,1) = 371.33;
    matrix(1,0) = 371.33; matrix(1,1) = 821.02;
    return matrix.Invert()*vec_mass*vec_mass;
}

double Chi2_calculator_improved(double w_mass, double t_mass, double fcnc_top_mass){
    TVectorD vec_mass(3);
    vec_mass(0) = w_mass - w_boson_mass;
    vec_mass(1) = t_mass - top_quark_mass;
    vec_mass(2) = fcnc_top_mass - top_quark_mass;
    TMatrixD matrix(3,3);
    matrix(0,0) = 341.00; matrix(0,1) = 371.33; matrix(0,2) =   4.19;
    matrix(1,0) = 371.33; matrix(1,1) = 821.02; matrix(1,2) =  -0.21;
    matrix(2,0) =   4.19; matrix(2,1) =  -0.21; matrix(2,2) = 251.80;
    return matrix.Invert()*vec_mass*vec_mass;
}

/*************************
update: 201015-161129 
comment: covariance matrices derived from different sets of 2017 signal MC samples

covMatrix_st_hct.txt
dataset: /wk_cms2/youying/public/tH_FCNC/Era2017_RR-31Mar2018_v2/ST_FCNC-TH_Thadronic_HToaa_eta_hct-MadGraph5-pythia8.root
293.63, 311.78, -49.90
311.78, 750.56, 286.70
-49.90, 286.70, 2318.94

covMatrix_st_hut.txt
dataset: /wk_cms2/youying/public/tH_FCNC/Era2017_RR-31Mar2018_v2/ST_FCNC-TH_Thadronic_HToaa_eta_hut-MadGraph5-pythia8.root
311.16, 328.93, -63.03
328.93, 783.41, 247.75
-63.03, 247.75, 2311.54

covMatrix_tt_hct.txt
dataset: /wk_cms2/youying/public/tH_FCNC/Era2017_RR-31Mar2018_v2/TT_FCNC-aTtoHJ_Thadronic_HToaa_eta_hct-MadGraph5-pythia8.root, /wk_cms2/youying/public/tH_FCNC/Era2017_RR-31Mar2018_v2/TT_FCNC-TtoHJ_aThadronic_HToaa_eta_hct-MadGraph5-pythia8.root
341.00, 371.33,   4.19
371.33, 821.02,  -0.21
  4.19,  -0.21, 251.80

covMatrix_tt_hut.txt
dataset: /wk_cms2/youying/public/tH_FCNC/Era2017_RR-31Mar2018_v2/TT_FCNC-aTtoHJ_Thadronic_HToaa_eta_hut-MadGraph5-pythia8.root, /wk_cms2/youying/public/tH_FCNC/Era2017_RR-31Mar2018_v2/TT_FCNC-TtoHJ_aThadronic_HToaa_eta_hut-MadGraph5-pythia8.root
344.31, 375.30,   7.95
375.30, 837.23,  -4.34
  7.95,  -4.34, 242.73
*************************/
